/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import engine.Mahasiswa;
import engine.SOM;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ermengarde
 */
public class ApplicationGUI extends javax.swing.JFrame {
    JFileChooser jf;
    HashMap<String, Integer> hmGender;
    HashMap<String, Integer> hmJurusan;
    HashMap<String, Integer> hmHobi;
    HashMap<String, Integer> hmKotaAsal;
    HashMap<String, Integer> hmFrekuensiAkses;
    ArrayList<Mahasiswa> trainingSet;
    ArrayList<Mahasiswa> dataSet;
    SOM som;
    
    /**
     * Creates new form ApplicationGUI
     */
    public ApplicationGUI() {
        initComponents();
        trainingSet = new ArrayList<>();
        dataSet = new ArrayList<>();
        dataSet = new ArrayList<>();
        hmGender  = new HashMap<>();
        hmJurusan  = new HashMap<>();
        hmHobi  = new HashMap<>();
        hmKotaAsal  = new HashMap<>();
        hmFrekuensiAkses  = new HashMap<>();
        //gender
        hmGender.put("laki-laki", 1);
        hmGender.put("perempuan", 2);
        //jurusan
        hmJurusan.put("ekonomi pembangunan", 11);
        hmJurusan.put("manajemen", 12);
        hmJurusan.put("akuntansi", 13);
        hmJurusan.put("ilmu hukum", 21);
        hmJurusan.put("ilmu administrasi publik", 31);
        hmJurusan.put("ilmu administrasi bisnis", 32);
        hmJurusan.put("ilmu hubungan internasional", 33);
        hmJurusan.put("teknik sipil", 41);
        hmJurusan.put("arsitektur", 42);
        hmJurusan.put("ilmu filsafat", 51);
        hmJurusan.put("teknik industri", 61);
        hmJurusan.put("teknik kimia", 62);
        hmJurusan.put("teknik elektro", 63);
        hmJurusan.put("matematika", 71);
        hmJurusan.put("fisika", 72);
        hmJurusan.put("informatika", 73);
        //hobi
        hmHobi.put("olahraga", 10);
        hmHobi.put("berkebun", 20);
        hmHobi.put("masak", 30);
        hmHobi.put("belanja", 40);
        hmHobi.put("lainnya", 50);
        //kota asal
        hmKotaAsal.put("jakarta", 5);
        hmKotaAsal.put("bandung", 10);
        hmKotaAsal.put("surabaya", 15);
        hmKotaAsal.put("medan", 20);
        hmKotaAsal.put("tanggerang", 25);
        hmKotaAsal.put("bekasi", 30);
        hmKotaAsal.put("lampung", 35);
        hmKotaAsal.put("solo", 40);
        hmKotaAsal.put("malang", 45);
        hmKotaAsal.put("riau", 50);
        hmKotaAsal.put("madura", 55);
        hmKotaAsal.put("yogyakarta", 60);
        hmKotaAsal.put("aceh", 65);
        hmKotaAsal.put("lainnya", 0);
        //frekuensi akses
        hmFrekuensiAkses.put("setiap hari", 50);
        hmFrekuensiAkses.put("2 - 3 hari sekali", 40);
        hmFrekuensiAkses.put("4 - 7 hari sekali", 30);
        hmFrekuensiAkses.put("sebulan sekali", 20);
        hmFrekuensiAkses.put("> sebulan sekali", 10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        homeMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clusterDataButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        trainSOMButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        weightMatrix = new javax.swing.JTable();
        clusterData = new javax.swing.JPanel();
        clusterDataMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        homeButton = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        openDataSetButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        clusterDatasetButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataSetTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        trainSOM = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        homeButton2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        openTrainingSet = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        trainTheSOM = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        learningRate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        maxEphoc = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        trainingSetTable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));

        homeMenu.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");

        clusterDataButton.setBackground(new java.awt.Color(204, 204, 204));
        clusterDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clusterDataButtonMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Refresh_96px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cluster Data");

        javax.swing.GroupLayout clusterDataButtonLayout = new javax.swing.GroupLayout(clusterDataButton);
        clusterDataButton.setLayout(clusterDataButtonLayout);
        clusterDataButtonLayout.setHorizontalGroup(
            clusterDataButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clusterDataButtonLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        clusterDataButtonLayout.setVerticalGroup(
            clusterDataButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
            .addGroup(clusterDataButtonLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4))
        );

        trainSOMButton.setBackground(new java.awt.Color(204, 204, 204));
        trainSOMButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                trainSOMButtonMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Increase_96px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Train SOM");

        javax.swing.GroupLayout trainSOMButtonLayout = new javax.swing.GroupLayout(trainSOMButton);
        trainSOMButton.setLayout(trainSOMButtonLayout);
        trainSOMButtonLayout.setHorizontalGroup(
            trainSOMButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainSOMButtonLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        trainSOMButtonLayout.setVerticalGroup(
            trainSOMButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
            .addGroup(trainSOMButtonLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6))
        );

        javax.swing.GroupLayout homeMenuLayout = new javax.swing.GroupLayout(homeMenu);
        homeMenu.setLayout(homeMenuLayout);
        homeMenuLayout.setHorizontalGroup(
            homeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(homeMenuLayout.createSequentialGroup()
                        .addComponent(trainSOMButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clusterDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(806, Short.MAX_VALUE))
        );
        homeMenuLayout.setVerticalGroup(
            homeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homeMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clusterDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(trainSOMButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel7.setText("Matrix Bobot:");

        weightMatrix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "e-commerce", "social media", "entertainment", "education"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(weightMatrix);

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(homeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(home, "card2");

        clusterData.setBackground(new java.awt.Color(255, 255, 255));

        clusterDataMenu.setBackground(new java.awt.Color(153, 153, 255));
        clusterDataMenu.setForeground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cluster Data");

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeButtonMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Back to Home");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Home_96px.png"))); // NOI18N

        javax.swing.GroupLayout homeButtonLayout = new javax.swing.GroupLayout(homeButton);
        homeButton.setLayout(homeButtonLayout);
        homeButtonLayout.setHorizontalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeButtonLayout.setVerticalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(33, 33, 33))
        );

        openDataSetButton.setBackground(new java.awt.Color(204, 204, 204));
        openDataSetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openDataSetButtonMousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Open_96px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Open Dataset");

        javax.swing.GroupLayout openDataSetButtonLayout = new javax.swing.GroupLayout(openDataSetButton);
        openDataSetButton.setLayout(openDataSetButtonLayout);
        openDataSetButtonLayout.setHorizontalGroup(
            openDataSetButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openDataSetButtonLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        openDataSetButtonLayout.setVerticalGroup(
            openDataSetButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openDataSetButtonLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(openDataSetButtonLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clusterDatasetButton.setBackground(new java.awt.Color(204, 204, 204));
        clusterDatasetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clusterDatasetButtonMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cluster Data");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Refresh_96px.png"))); // NOI18N

        javax.swing.GroupLayout clusterDatasetButtonLayout = new javax.swing.GroupLayout(clusterDatasetButton);
        clusterDatasetButton.setLayout(clusterDatasetButtonLayout);
        clusterDatasetButtonLayout.setHorizontalGroup(
            clusterDatasetButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clusterDatasetButtonLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clusterDatasetButtonLayout.setVerticalGroup(
            clusterDatasetButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clusterDatasetButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clusterDatasetButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout clusterDataMenuLayout = new javax.swing.GroupLayout(clusterDataMenu);
        clusterDataMenu.setLayout(clusterDataMenuLayout);
        clusterDataMenuLayout.setHorizontalGroup(
            clusterDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clusterDataMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clusterDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clusterDataMenuLayout.createSequentialGroup()
                        .addComponent(openDataSetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clusterDatasetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clusterDataMenuLayout.setVerticalGroup(
            clusterDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clusterDataMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(clusterDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openDataSetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clusterDatasetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        dataSetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Gender", "Jurusan", "Hobi", "Kota Asal", "Frekuensi Mengakses Internet", "Cluster"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(dataSetTable);

        jLabel14.setText("Dataset:");

        javax.swing.GroupLayout clusterDataLayout = new javax.swing.GroupLayout(clusterData);
        clusterData.setLayout(clusterDataLayout);
        clusterDataLayout.setHorizontalGroup(
            clusterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clusterDataMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(clusterDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clusterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(clusterDataLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        clusterDataLayout.setVerticalGroup(
            clusterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clusterDataLayout.createSequentialGroup()
                .addComponent(clusterDataMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(clusterData, "card3");

        trainSOM.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        homeButton2.setBackground(new java.awt.Color(204, 204, 204));
        homeButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeButton2MousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Back to Home");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Home_96px.png"))); // NOI18N

        javax.swing.GroupLayout homeButton2Layout = new javax.swing.GroupLayout(homeButton2);
        homeButton2.setLayout(homeButton2Layout);
        homeButton2Layout.setHorizontalGroup(
            homeButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButton2Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeButton2Layout.setVerticalGroup(
            homeButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButton2Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeButton2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(40, 40, 40))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Train SOM");

        openTrainingSet.setBackground(new java.awt.Color(204, 204, 204));
        openTrainingSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openTrainingSetMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Open Trainingset");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Open_96px.png"))); // NOI18N

        javax.swing.GroupLayout openTrainingSetLayout = new javax.swing.GroupLayout(openTrainingSet);
        openTrainingSet.setLayout(openTrainingSetLayout);
        openTrainingSetLayout.setHorizontalGroup(
            openTrainingSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openTrainingSetLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        openTrainingSetLayout.setVerticalGroup(
            openTrainingSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openTrainingSetLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openTrainingSetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(31, 31, 31))
        );

        trainTheSOM.setBackground(new java.awt.Color(204, 204, 204));
        trainTheSOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                trainTheSOMMousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Train SOM");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Increase_96px.png"))); // NOI18N

        javax.swing.GroupLayout trainTheSOMLayout = new javax.swing.GroupLayout(trainTheSOM);
        trainTheSOM.setLayout(trainTheSOMLayout);
        trainTheSOMLayout.setHorizontalGroup(
            trainTheSOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainTheSOMLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trainTheSOMLayout.setVerticalGroup(
            trainTheSOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainTheSOMLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trainTheSOMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(33, 33, 33))
        );

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Jumlah Ephoc Maksimal");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Learning Rate");

        maxEphoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxEphocActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText(":");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(openTrainingSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trainTheSOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(homeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(539, 539, 539))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxEphoc)
                            .addComponent(learningRate))
                        .addGap(721, 721, 721))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(maxEphoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(learningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openTrainingSet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(trainTheSOM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        trainingSetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Gender", "Jurusan", "Hobi", "Kota Asal", "Frekuensi Mengakses Internet"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(trainingSetTable);

        jLabel22.setText("Trainingset:");

        javax.swing.GroupLayout trainSOMLayout = new javax.swing.GroupLayout(trainSOM);
        trainSOM.setLayout(trainSOMLayout);
        trainSOMLayout.setHorizontalGroup(
            trainSOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(trainSOMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trainSOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(trainSOMLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        trainSOMLayout.setVerticalGroup(
            trainSOMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainSOMLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(trainSOM, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMousePressed
        background.removeAll();
        background.repaint();
        background.revalidate();
        
        background.add(home);
        background.repaint();
        background.revalidate();
    }//GEN-LAST:event_homeButtonMousePressed

    private void clusterDataButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clusterDataButtonMousePressed
        background.removeAll();
        background.repaint();
        background.revalidate();
        
        background.add(clusterData);
        background.repaint();
        background.revalidate();
    }//GEN-LAST:event_clusterDataButtonMousePressed

    private void trainSOMButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainSOMButtonMousePressed
        background.removeAll();
        background.repaint();
        background.revalidate();
        
        background.add(trainSOM);
        background.repaint();
        background.revalidate();
    }//GEN-LAST:event_trainSOMButtonMousePressed

    private void openDataSetButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openDataSetButtonMousePressed
        jf = new JFileChooser(new File("C:/"));
        jf.setFileFilter(new FileNameExtensionFilter("CSV files", "csv"));
        jf.setDialogTitle("Choose CSV File");
        int feedback = jf.showOpenDialog(this);
        final String inputURI = jf.getSelectedFile().getAbsolutePath();
        if(feedback == JFileChooser.APPROVE_OPTION){
            File selectedFile = jf.getSelectedFile();
            try{
                BufferedReader br = new BufferedReader(new FileReader(selectedFile));
                String buffer;
                String buffers[];
                while((buffer=br.readLine())!=null){
                    buffer = buffer.toLowerCase();
                    buffers = buffer.split(";");
                    String mNama = buffers[0];
                    int mGender = hmGender.get(buffers[1]);
                    int mJurusan = hmJurusan.get(buffers[2]);
                    int mHobi = hmHobi.get(buffers[3]);
                    int mKotaAsal = hmKotaAsal.get(buffers[4]);
                    int mFrekuensiAkses = hmFrekuensiAkses.get(buffers[5]);
                    String mJenisApkOnline = buffers[6];
                    dataSet.add(new Mahasiswa(mNama, mGender, mKotaAsal, mFrekuensiAkses, mJurusan, mHobi, mJenisApkOnline));
                }
                DefaultTableModel dtm2 = (DefaultTableModel) dataSetTable.getModel();
                Object rowData[] = new Object[7];
                for(int i=0;i<dataSet.size();i++){
                    rowData[0] = dataSet.get(i).getNama();
                    rowData[1] = dataSet.get(i).getGender();
                    rowData[2] = dataSet.get(i).getJurusan();
                    rowData[3] = dataSet.get(i).getHobi();
                    rowData[4] = dataSet.get(i).getKotaAsal();
                    rowData[5] = dataSet.get(i).getFrekuensiAkses();
                    rowData[6] = "";
                    dtm2.addRow(rowData);
                }
            } catch(IOException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_openDataSetButtonMousePressed

    private void clusterDatasetButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clusterDatasetButtonMousePressed
        som.setDataSet(dataSet);
        ArrayList<Integer> clusters = som.clusterDataSet();
        DefaultTableModel dtm2 = (DefaultTableModel) dataSetTable.getModel();
        int rowCount = dtm2.getRowCount();
        for(int i=rowCount-1;i>=0;i--){
            dtm2.removeRow(i);
        }
        Object rowData[] = new Object[7];
        for(int i=0;i<dataSet.size();i++){
            rowData[0] = dataSet.get(i).getNama();
            rowData[1] = dataSet.get(i).getGender();
            rowData[2] = dataSet.get(i).getJurusan();
            rowData[3] = dataSet.get(i).getHobi();
            rowData[4] = dataSet.get(i).getKotaAsal();
            rowData[5] = dataSet.get(i).getFrekuensiAkses();
            if(clusters.get(i)==0){
                rowData[6] = "e-commerce";
            }
            else if(clusters.get(i)==1){
                rowData[6] = "social media";
            }
            else if(clusters.get(i)==2){
                rowData[6] = "entertainment";
            }
            else if(clusters.get(i)==3){
                rowData[6] = "education";
            }
            dtm2.addRow(rowData);
        }
    }//GEN-LAST:event_clusterDatasetButtonMousePressed

    private void maxEphocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxEphocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxEphocActionPerformed

    private void trainTheSOMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainTheSOMMousePressed
        Integer maxEphoc = Integer.parseInt(this.maxEphoc.getText());
        Double learningRate = Double.parseDouble(this.learningRate.getText());
        this.som = new SOM(this.trainingSet, learningRate, maxEphoc);
        DefaultTableModel dtm = (DefaultTableModel) weightMatrix.getModel();
        Object rowData[] = new Object[this.som.getNumInputNode()];
        for(int i=0;i<this.som.getNumInputNode();i++){
            if(i==0){
                rowData[0] = "Gender";
            }
            else if(i==1){
                rowData[0] = "Jurusan";
            }
            else if(i==2){
                rowData[0] = "Hobi";
            }
            else if(i==3){
                rowData[0] = "Kota Asal";
            }
            else if(i==4){
                rowData[0] = "Frekuensi Mengakses Internet";
            }
            rowData[1] = this.som.getWeightMatrix()[i][0];
            rowData[2] = this.som.getWeightMatrix()[i][1];
            rowData[3] = this.som.getWeightMatrix()[i][2];
            rowData[4] = this.som.getWeightMatrix()[i][3];
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_trainTheSOMMousePressed

    private void openTrainingSetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openTrainingSetMousePressed
        jf = new JFileChooser(new File("C:/"));
        jf.setFileFilter(new FileNameExtensionFilter("CSV files", "csv"));
        jf.setDialogTitle("Choose CSV File");
        int feedback = jf.showOpenDialog(this);
        final String inputURI = jf.getSelectedFile().getAbsolutePath();
        if(feedback == JFileChooser.APPROVE_OPTION){
            File selectedFile = jf.getSelectedFile();
            try{
                BufferedReader br = new BufferedReader(new FileReader(selectedFile));
                String buffer;
                String buffers[];
                while((buffer=br.readLine())!=null){
                    buffer = buffer.toLowerCase();
                    buffers = buffer.split(";");
                    String mNama = buffers[0];
                    int mGender = hmGender.get(buffers[1]);
                    int mJurusan = hmJurusan.get(buffers[2]);
                    int mHobi = hmHobi.get(buffers[3]);
                    int mKotaAsal = hmKotaAsal.get(buffers[4]);
                    int mFrekuensiAkses = hmFrekuensiAkses.get(buffers[5]);
                    String mJenisApkOnline = buffers[6];
                    trainingSet.add(new Mahasiswa(mNama, mGender, mKotaAsal, mFrekuensiAkses, mJurusan, mHobi, mJenisApkOnline));
                }
                DefaultTableModel dtm = (DefaultTableModel) trainingSetTable.getModel();
                Object rowData[] = new Object[6];
                for(int i=0;i<trainingSet.size();i++){
                    rowData[0] = trainingSet.get(i).getNama();
                    rowData[1] = trainingSet.get(i).getGender();
                    rowData[2] = trainingSet.get(i).getJurusan();
                    rowData[3] = trainingSet.get(i).getHobi();
                    rowData[4] = trainingSet.get(i).getKotaAsal();
                    rowData[5] = trainingSet.get(i).getFrekuensiAkses();
                    dtm.addRow(rowData);
                }
            } catch(IOException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_openTrainingSetMousePressed

    private void homeButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton2MousePressed
        background.removeAll();
        background.repaint();
        background.revalidate();

        background.add(home);
        background.repaint();
        background.revalidate();
    }//GEN-LAST:event_homeButton2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel clusterData;
    private javax.swing.JPanel clusterDataButton;
    private javax.swing.JPanel clusterDataMenu;
    private javax.swing.JPanel clusterDatasetButton;
    private javax.swing.JTable dataSetTable;
    private javax.swing.JPanel home;
    private javax.swing.JPanel homeButton;
    private javax.swing.JPanel homeButton2;
    private javax.swing.JPanel homeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField learningRate;
    private javax.swing.JTextField maxEphoc;
    private javax.swing.JPanel openDataSetButton;
    private javax.swing.JPanel openTrainingSet;
    private javax.swing.JPanel trainSOM;
    private javax.swing.JPanel trainSOMButton;
    private javax.swing.JPanel trainTheSOM;
    private javax.swing.JTable trainingSetTable;
    private javax.swing.JTable weightMatrix;
    // End of variables declaration//GEN-END:variables
}
